### ISSUE TITLE
How to remove Header

### ISSUE THREAD

**Issue by sachinkhanna55** [psergus/ngWYSIWYG#35]
Hi,

I am using 3 instances of text editor in a page.

On 1 instance, I want to remove header of text editor.

Please help.

**Comment by brunokrebs** [comment]
What do you mean by 'remove header'? Do you mean the place that contains the buttons? You wan't no buttons?

**Comment by brunokrebs** [comment]
If that is what you want you could easily do that with CSS, like that:

```css
div.tinyeditor-header {
    display: none;
}
```
